# tag::kernel-slim[]
FROM icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi
# end::kernel-slim[]

# tag::config[]
COPY --chown=1001:0 src/main/liberty/config/ /config/
# end::config[]

# tag::features[]
RUN features.sh
# end::features[]

# tag::war[]
COPY --chown=1001:0 target/guide-instanton-aws-system.war /config/apps
# end::war[]

# tag::configure[]
RUN configure.sh
# end::configure[]

# tag::checkpoint[]
# You can use beforeAppStart or afterAppStart to do the checkpoint.
# The default is beforeAppStart when not specified
RUN checkpoint.sh afterAppStart
# end::checkpoint[]
