# tag::system[]
apiVersion: apps.openliberty.io/v1
# tag::olapp[]
kind: OpenLibertyApplication
# end::olapp[]
metadata:
  name: system
spec:
  # tag::sysImage[]
  applicationImage: [system-repository-uri]:1.0-SNAPSHOT
  # end::sysImage[]
  pullPolicy: Always
  manageTLS: true
  replicas: 2
  service:
  # tag::serviceType[]
    type: NodePort
    # end::serviceType[]
    port: 9443
    targetPort: 9443
    nodePort: 31000
  expose: true
  route:
    certificateSecretRef: tls-secret
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: simple 
  # tag::securityContext[]
  securityContext:
    # tag::runAsNonRoot[]
    runAsNonRoot: true
    # end::runAsNonRoot[]
    privileged: false
    allowPrivilegeEscalation: true
    # tag::capabilities[]
    capabilities:
      add:
        - CHECKPOINT_RESTORE
        - SETPCAP
      drop:
        - ALL
      # end::capabilities[]
  # end::securityContext[]
  # tag::semeruCloudCompiler[]
  semeruCloudCompiler:
  # tag::enable[]
    enable: true
    # end::enable[]
    replicas: 1
  # end::semeruCloudCompiler[]
# end::system[]
