
apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: system
  labels:
    name: system
spec:
  applicationImage: [system-repository-uri]:1.0-SNAPSHOT
  # pullPolicy: IfNotPresent
  # manageTLS: false
  # replicas: 3
  # resources:
  #   limits:
  #     cpu: 1
  #     memory: 512Mi
  #   requests:
  #     cpu: 500m
  #     memory: 256Mi
  service:
    type: ClusterIP
    port: 9443
  expose: true
  securityContext:
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: true
    capabilities:
      add:
      - CHECKPOINT_RESTORE
      - SETPCAP
      drop:
      - ALL
  semeruCloudCompiler:
    enable: true
    replicas: 3

# spec:
  # applicationImage: system:1.0-SNAPSHOT
  # service:
  #   port: 9443
  # expose: true
  route:
    pathType: ImplementationSpecific
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"